### ISSUE TITLE
Videos player not present when browsing pages

### ISSUE THREAD

**Issue by fjs138** [muxinc/video-course-starter-kit#38]
I cannot get videos/the video player to appear, but they work in your demo.

I have tried building and setting it up on multiple machines, using different versions of Node (v18.14.2, v16.13.0, v20) and npm package versions, among other variations. Despite my efforts, I am unable to figure out what the problem is. I'm not seeing any warnings, errors, or peculiarities. 

When I access the site both locally and on Vercel, I notice that where videos should be displayed, there is just a grey background. After inspecting your live, working demo and comparing it to mine, I can see that your version has video player elements while mine are missing.

The videos are indeed going into my mux video bucket and the entries are being created in the database, so it seems to be related to invoking the player itself in the browser.
.

I wonder if some incompatibility has arose over time and your demo is prior to that issue.

**Comment by DigitalPotential** [comment]
I seem to have the same problem, would love to see this be resolved.

I will continue check if I have configured the starter kit correctly to see If I can find the issue.

Best Regards,
Carlos Manriquez

**Comment by dylanjha** [comment]
@fjs138 & @DigitalPotential thank you for opening this!

Can you share a repo or link to a deployed example that We can take a look at?

**Comment by DigitalPotential** [comment]
I actually resolved my issue with the video player not showing.

What I think was missing was the webhook.
Reading the documentation I misunderstood it and though it was optional to use a webhook for the starter kit to work.

Hopefully @fjs138 can resolve his issue the same way.

@dylanjha Thank you for this starter kit which has helped me learn more about how Mux works, hopefully I will have the opportunity to use it on a live project soon.

**Comment by davekiss** [comment]
Glad to see that this was resolved! I'm going to close this ticket due to inactivity/resolution, but please feel free to open a new ticket if your problem does persist
